# Generated by Django 5.2.5 on 2025-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='problem_resolved',
            field=models.TextField(blank=True, help_text='Description of how the problem was resolved', null=True),
        ),
    ]
