# Generated by Django 5.2.5 on 2025-08-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceitem_problem_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('received', 'Payment Received'), ('partial', 'Partial Payment')], default='pending', max_length=20),
        ),
    ]
